blueprint:
  name: Calibrate Sonoff TRV external temperature
  description: Calibrate Sonoff TRV internal temperature according to external temperature sensor
  domain: automation
  input:
    external_temp:
      name: Select the external temp sensor
      description: This will be your external temp sensor.
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - temperature
          multiple: false
    trv_names:
      name: TRV entries
      description: This will be the Sonoff TRVs that will be calibrated using the external sensor.
      selector:
        entity:
          domain:
          - climate
          multiple: true
    min_change:
      name: Minimum Temperature Change
      description: Minimum temperature change to trigger update (prevents excessive updates)
      default: 0.3
      selector:
        number:
          min: 0.1
          max: 2.0
          unit_of_measurement: "°C"
          mode: slider
          step: 0.1
  source_url: https://github.com/kvanbiesen/HASonoffAutomation/SyncexternaltempSonoff.yaml
alias: Calibrate Sonoff TRVs
description: ''
variables:
  trv_names: !input trv_names
  external_temperature: !input external_temp
  min_temperature_change: !input min_change
trigger:
- platform: state
  entity_id: !input external_temp
  for:
    hours: 0
    minutes: 0
    seconds: 15
    milliseconds: 0
- platform: state
  entity_id: !input trv_names
  for:
    hours: 0
    minutes: 0
    seconds: 15
    milliseconds: 0
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{ states(external_temperature) != ''unavailable'' }}'
  - condition: template
    value_template: '{{ states(external_temperature) != ''unknown'' }}'
action:
- repeat:
    for_each: "{{ trv_names }}"
    sequence:
    - variables:
        trv_name: "{{ repeat.item }}"
        trv_external_entity: "number.sonoff_trvzb_external_temperature_sensor_value"
        ##trv_external_entity: "number.{{ trv_name.removeprefix('climate.') }}_external_temperature_sensor_value"
        trv_external_temp: "{{ states(trv_external_entity) | float() }}"
        sensor_external_temp: "{{ states(external_temperature) | float() }}"
        local_temp: "{{ state_attr(trv_name, 'current_temperature') | float() }}"
        target_temp: "{{ state_attr(trv_name, 'temperature') | float() }}"
        temp_diff: "{{ (sensor_external_temp - trv_external_temp) | abs() }}"

    - alias: "check if calibration needs change"
      condition: template
      value_template: "{{ (temp_diff | round(1)) >= min_temperature_change }}"

    - service: number.set_value
      target:
        entity_id: "{{ device_external_entity }}"
      data:
        value: "{{ sensor_external_temp }}"

    - service: logbook.log
      data:
        name: "Calibration Update"
        message: >-
          Calibrating {{ trv_name }}. External sensor is {{ sensor_external_temp }}°C.
          Previous TRV external value was {{ device_external_temp }}°C.
          Setting new value on {{ device_external_entity }}.

- delay: 5
mode: single
max_exceeded: silent
